config/routes.rb
RedmineApp::Application.routes.draw do
  resources :domains, except: :destroy do
    collection do
      get :context_menu
    end
    member do
      get :hide_or_show
    end
  end

  get 'projects/:id/accesses', to: 'accesses#index', as: 'project_accesses'
  resources :accesses, except: :destroy
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  unloadable
  model_object Access
  before_filter :find_model_object, except: [:index, :new, :create]
  before_filter :find_project, only: :index

  after_filter only: [:create, :edit, :update] do |controller|
    if controller.request.post?
      controller.send :expire_action, controller: 'welcome', action: 'robots'
    end
  end

  def index
    @accesses = @project.accesses.includes(:category)
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def new
    @access = Access.new
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def create
    @access = Access.new(params[:access])
    respond_to do |format|
      if @access.save
        format.html { redirect_to (params[:continue] ? { action: :new } : @access),
                                  notice: l(:notice_successful_create) }
        format.js { redirect_to (params[:continue] ? { action: :new } : access_path(@access)),
                           notice: l(:notice_successful_create) }
      else
        format.html { render action: :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @access.update_attributes(params[:access])
        format.html { redirect_to @access,
                      notice: l(:notice_successful_update) }
        format.js { redirect_to action: :show,
                           notice: l(:notice_successful_update) }
      else
        format.html { render action: :edit }
        format.js
      end
    end
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_accesses.html.erb
<h2>
  <div class="contextual">
    <% if is_domains_show? -%>
      <%= link_to l(:label_access_new), { controller: 'accesses', action: 'new', params: { project_id: @domain.project.identifier }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% else -%>
      <%= link_to l(:label_access_new), { controller: 'accesses', action: 'new', params: { project_id: params[:id] }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% end %>
  </div>
  <div class="clearfix"></div>
</h2>

<% unless @accesses.nil? || @accesses.empty? -%>
  <div class="autoscroll">
    <table class="list accesses mdl-data-table mdl-shadow--1dp">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_access) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_url) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_login) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_password) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_description) %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @accesses.each do |access| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to access.category, access_path(id: access.id), remote: true %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.url %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.login %>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.password %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.description %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/accesses/_edit.html.erb
<h2>
  <%= link_to l(:label_access_plural), project_accesses_path(@access.project), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <button class='mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect'>
    <%= l(:label_access_edit) %>
  </button>
</h2>

<%= labelled_form_for :access, @access, url: { controller: 'accesses', action: 'update', params: params }, html: { class: nil, 'data-remote' => 'true' } do |f| -%>
	<%= render partial: 'form', locals: { f: f, params: params } %>
	<h2><%= submit_tag l(:button_update), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %></h2>
<% end %>

app/views/accesses/_form.html.erb
<%= error_messages_for 'access' %>

<div class="box tabular">
  <p><%= f.select :category_id, AccessCategory.active.collect {|c| [c.name, c.id]} %></p>
  <p><%= f.select :domain_id, options_from_collection_for_select(Domain.visible, :id, :name, @access.domain_id),
{ include_blank: true, label: :label_domain } %></p>
  <p><%= f.text_field :url, class: "mdl-textfield__input" %></p>
  <p><%= f.text_field :login, class: "mdl-textfield__input" %></p>
  <p><%= f.text_field :password, class: "mdl-textfield__input" %></p>
  <p><%= f.text_area :description, class: "mdl-textfield__input" %></p>
</div>

app/views/accesses/_index.html.erb
<h2>
  <div class="contextual">
    <% if is_domains_show? -%>
      <%= link_to l(:label_access_new), { controller: 'accesses', action: 'new', params: { project_id: @domain.project.identifier }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% else -%>
      <%= link_to l(:label_access_new), { controller: 'accesses', action: 'new', params: { project_id: params[:id] }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% end %>
  </div>
  <div class="clearfix"></div>
</h2>

<% unless @accesses.nil? || @accesses.empty? -%>
  <div class="autoscroll">
    <table class="list accesses mdl-data-table mdl-shadow--1dp">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_access) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_url) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_login) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_password) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_description) %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @accesses.each do |access| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to access.category, access_path(id: access.id), remote: true %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.url %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.login %>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.password %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= access.description %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/accesses/_new.html.erb
<h2>
  <%= link_to l(:label_access_plural), project_accesses_path(Project.find(params[:project_id].nil? ? Project.visible.last.id : params[:project_id])), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <button class='mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect'>
    <%=l(:label_access_new) %>
  </button>
</h2>

<%= labelled_form_for :access, @access, url: { controller: 'accesses', action: 'create', params: { project_id: params[:project_id] } }, html: { class: nil, 'data-remote' => 'true' } do |f| -%>
	<%= render partial: 'form', locals: { f: f, params: params } %>
	<h2>
    <%= submit_tag l(:button_create), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <%= submit_tag l(:button_create_and_continue), name: 'continue', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
  </h2>
<% end -%>

app/views/accesses/_show.html.erb
<h2>
  <%= link_to l(:label_access_plural), project_accesses_path(@access.project), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <%= link_to l(:label_access_edit), { controller: 'accesses', action: 'edit', id: @access }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--indigo-400 mdl-js-ripple-effect' %>
</h2>

<div class="box">
  <h3><%= @access.category %></h3>
  <p class="wiki description">
    <%= @access.description %>
  </p>
  <% if @access.domain -%>
    <p><%= l(:label_domain) %>: <%= link_to @access.domain.name, domain_path(@access.domain), remote: true %></p>
  <% end %>
  <p><%= l(:field_url) %>: <%= @access.url %></p>
  <p><%= l(:field_login) %>: <%= @access.login %></p>
  <p><%= l(:field_password) %>: <%= @access.password %></p>
</div>

app/views/accesses/create.js.erb
$.ajax({
    type: "POST",
    dataType: "script",
    url: "<%= access_path(@access) %>",
    contentType: 'application/json',
    data: JSON.stringify({ params[:access], _method: 'patch' })
})

app/views/accesses/edit.html.erb
<%= render partial: 'edit', locals: { access: @access } %>

app/views/accesses/index.html.erb
<%= render partial: 'accesses', locals: { accesses: @accesses } %>

app/views/accesses/new.html.erb
<%= render partial: 'new', locals: { access: @access } %>

app/views/accesses/show.html.erb
<%= render partial: 'show', locals: { access: @access } %>

app/views/accesses/update.js.erb
$.ajax({
    type: 'POST',
    dataType: 'script',
    url: "<%= access_path(@access) %>",
    contentType: 'application/json',
    data: JSON.stringify({ params[:access], _method: 'patch' })
})