config/routes.rb
RedmineApp::Application.routes.draw do
  resources :domains, except: :destroy do
    collection do
      get :context_menu
    end
    member do
      get :hide_or_show
    end
  end

  get 'projects/:id/accesses', to: 'accesses#index', as: 'project_accesses'
  resources :accesses, except: :destroy
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes

  acts_as_customizable
  acts_as_activity_provider type: 'domains',
                            author_key: :author_id,
                            timestamp: :created_at,
                            scope: joins(:project)

  acts_as_searchable columns: ["#{table_name}.name",
                               "#{table_name}.status",
                               "#{Access.table_name}.category",
                               "#{Access.table_name}.url",
                               "#{Access.table_name}.login",
                               "#{Access.table_name}.password",
                               "#{Access.table_name}.description"],
                     scope: includes(:project, :accesses),
                     project_key: "#{Project.table_name}.id",
                     date_column: 'created_at'

  acts_as_event datetime: :created_at,
                title: Proc.new {|d| "#{l(:label_domain)}: #{d.name}"},
                url: Proc.new {|d| { controller: 'domains',
                                     action: 'show', id: d}},
                description: lambda { |d| [d.name, d.project, d.status,
                                           d.accesses.includes(:category).
                                             map(&:category).join(', '),
                                           d.ending_date].join(' ') }

  safe_attributes 'name', 'status', 'accesses', 'hidden', 'checked',
                  'author_id', 'ending_date', 'hosting', 'visibility',
                  'project_id', 'custom_field_values', 'custom_fields'
  attr_protected :id
  validates_presence_of :name, :project_id
  belongs_to :project
  has_many :accesses, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  scope :visible, lambda { |*args|
    joins(:project).where(Domain.visible_condition(args.shift || User.current, *args)) }

  scope :hidden, lambda { where(hidden: true) }
  scope :domains, lambda { where(hosting: false) }
  scope :hostings, lambda { where(hosting: true) }
  scope :month, lambda { where("ending_date BETWEEN ? AND ?",
                               Date.today.at_beginning_of_month,
                               (Date.today + 1.months).at_beginning_of_month) }

  def self.table(params)
    scope = if params[:hosting] == '1'
              self.visible.hostings
            else
              self.visible.domains
            end
    if params[:hidden] == '1'
      if params[:hostings] == '1'
        scope.hidden
      else
        scope.hidden
      end
    elsif params[:month] == '1'
      scope.month
    else
      scope
    end
  end

  def self.visible_condition(user, options={})
    user.reload
    user_ids = [user.id] + user.groups.map(&:id)

    projects_allowed_to_view_domains =
      Project.where(Project.allowed_to_condition(user, :view_domains)).pluck(:id)

    allowed_to_view_condition =
      projects_allowed_to_view_domains.empty? ? "(1=0)" :
        "#{Project.table_name}.id IN (#{projects_allowed_to_view_domains.join(',')})"

    projects_allowed_to_view_private =
      Project.where(Project.allowed_to_condition(user, :view_private_domains)).pluck(:id)

    allowed_to_view_private_condition =
      projects_allowed_to_view_private.empty? ? "(1=0)" :
        "#{Project.table_name}.id IN (#{projects_allowed_to_view_private.join(',')})"

    cond = "(#{Project.table_name}.id <> -1 ) AND ("
    if user.admin?
      cond << "(#{table_name}.visibility = 1) OR (#{allowed_to_view_condition}) "
    else
      cond << " (#{table_name}.visibility = 1) OR" if user.allowed_to_globally?(:view_domains, {})
      cond << " (#{allowed_to_view_condition} AND #{table_name}.visibility <> 2) "

      if user.logged?
        cond << " OR (#{allowed_to_view_private_condition} " +
                " OR (#{allowed_to_view_condition} " +
                " AND (#{table_name}.author_id = #{user.id} )))"
      end
    end

    cond << ")"
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  unloadable
  default_search_scope :domains
  model_object Domain
  before_filter :find_model_object,
                except: [:index, :new, :create, :context_menu]

  after_filter only: [:create, :edit, :update] do |controller|
    if controller.request.post?
      controller.send :expire_action, controller: 'welcome', action: 'robots'
    end
  end

  helper :custom_fields

  def index
    @domains = Domain.table(params)
    @custom_fields = DomainCustomField.all
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def show
    @accesses = @domain.accesses
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def new
    @domain = Domain.new
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js { render template: 'ajax/action' }
    end
  end

  def create
    @domain = Domain.new(params[:domain])
    respond_to do |format|
      if @domain.save
        format.html { redirect_to (params[:continue] ? { action: :new } : @domain),
                                  notice: l(:notice_successful_create) }
        format.js { redirect_to (params[:continue] ? { action: :new } : domain_path(@domain)),
                            notice: l(:notice_successful_create) }
      else
        format.html { render action: :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to @domain,
                      notice: l(:notice_successful_update) }
        format.js { redirect_to action: :show,
                           notice: l(:notice_successful_update) }
      else
        format.html { render action: :edit }
        format.js
      end
    end
  end

  def context_menu
    @domains = Domain.visible.where(id: params[:selected_domains])
    @domain = @domains.first if @domains.size == 1
    render layout: false
  end

  def hide_or_show
    @domain.update_attribute :hidden, (@domain.hidden? ? false : true)
    redirect_to domains_path
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
  def settings_domains_tabs
    [{ name: 'accesses', partial: 'settings/domains/accesses',
       label: :label_access_plural }]
  end

  def hide_or_show_link(domain)
    icon, id, label =
              if domain.hidden
                ['backup', "domain-show-#{domain.id}",
                 domain.hosting ? l(:label_hosting_show) : l(:label_domain_show)]
              else
                ['archive', "domain-hide-#{domain.id}",
                 domain.hosting ? l(:label_hosting_hide) : l(:label_domain_hide)]
              end
    link_to (content_tag(:i, icon, class: 'material-icons', id: id) +
             (content_tag(:span, label, class: 'mdl-tooltip', for: id))),
            hide_or_show_domain_path(domain)
  end

  def domain_title(domain)
    if domain.hosting
      domain.hidden? ? l(:label_hosting_hidden) : l(:label_hosting)
    else
      domain.hidden? ? l(:label_domain_hidden) : l(:label_domain)
    end
  end

  def statuses
    [l(:domain_service),
     l(:domain_self_service),
     l(:domain_not_access)]
  end

  def is_domains_show?
    route =
      Rails.application.routes.recognize_path(URI(request.path))
    if route[:controller] == 'domains' && route[:action] == 'show'
      true
    else
      false
    end
  end
end

app/views/domains/_domains.html.erb
<h2>
  <div class="contextual">
    <% if params[:hosting] == '1' -%>
      <%= link_to l(:label_hosting_new), { controller: 'domains', action: 'new', params: { hosting: '1' }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% else -%>
      <%= link_to l(:label_domain_new), { controller: 'domains', action: 'new', params: { hosting: '0' }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% end %>
  </div>

  <%= link_to l(:tab_domain_all), params.merge({month: '0', hosting: params[:hosting], hidden: '0'}), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <%= link_to l(:tab_domain_month), params.merge({month: '1', hosting: params[:hosting], hidden: '0'}), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect mdl-color-text--white' %>
  <%= link_to l(:tab_domain_hidden), params.merge({hidden: '1', hosting: params[:hosting], month: '0'}), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--indigo-400 mdl-js-ripple-effect mdl-color-text--white' %>
</h2>

<% unless @domains.nil? -%>
  <div class="autoscroll">
    <table class="list domains mdl-data-table mdl-shadow--1dp">
      <thead>
        <tr>
          <th class="hide-when-print mdl-data-table__cell--non-numeric">
            <%= image_tag('toggle_check.png') %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <% if params[:hosting] == '1' -%>
              <%= l(:label_hosting) %>
            <% else -%>
              <%= l(:label_domain) %>
            <% end %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:label_project) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_status) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_accesses) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_ending_date) %>
          </th>
          <% unless @custom_fields.nil? -%>
            <% @custom_fields.each do |field| -%>
              <th class="mdl-data-table__cell--non-numeric">
                <%= field.name %>
              </th>
            <% end %>
          <% end %>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:label_activity) %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @domains.each do |domain| %>
          <tr id="domain-<%= domain.id %>" class="hascontextmenu">
            <td class="hide-when-print mdl-data-table__cell--non-numeric"><%= check_box_tag("ids[]", domain.id, false, :id => nil) %></td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to domain.name, { controller: 'domains', action: 'show',
id: domain, params: { hosting: params[:hosting] } }, remote: true %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <% if domain.project.present? -%>
                <%= link_to domain.project.name, project_path(domain.project) %>
              <% end %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= domain.status %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <% unless domain.accesses.nil? -%>
                <% if domain.project -%>
                  <%= link_to domain.accesses.includes(:category).map(&:category).join(', '), project_accesses_path(domain.project), remote: true %>
                <% else -%>
                  <%= link_to domain.accesses.includes(:category).map(&:category).join(', '), domain_path(domain), remote: true %>
                <% end %>
              <% end %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= format_date(domain.ending_date) %>
            </td>
            <% unless domain.custom_field_values.nil? -%>
              <% domain.custom_field_values.each do |custom_value| -%>
                <td class="mdl-data-table__cell--non-numeric">
                  <%=h show_value(custom_value) %>
                </td>
              <% end %>
            <% end %>
            <td class="mdl-data-table__cell--non-numeric">
              <%= hide_or_show_link(domain) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= context_menu url_for( { controller: 'domains', action: 'context_menu', params: params } ) %>
<% else -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/domains/_edit.html.erb
<h2>
  <% if params[:hosting] -%>
    <%= link_to l(:label_hosting_plural), { controller: 'domains', action: 'index', params: { hosting: '1' } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <% else -%>
    <%= link_to l(:label_domain_plural), { controller: 'domains', action: 'index', params: { hosting: '0' } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <% end %>
  <% if @domain.hosting %>
    <button class='mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect'>
      <%= l(:label_hosting_edit) %>
    </button>
  <% else -%>
    <button class='mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect'>
      <%= l(:label_domain_edit) %>
    </button>
  <% end %>
</h2>

<%= labelled_form_for :domain, @domain, url: { controller: 'domains', action: 'update', params: { hosting: params[:hosting] } }, html: { class: nil, 'data-remote' => 'true' } do |f| -%>
	<%= render partial: 'form', locals: { f: f } %>
	<h2><%= submit_tag l(:button_update), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %></h2>
<% end %>

app/views/domains/_form.html.erb
<%= error_messages_for 'domain' %>

<div class="box tabular">
  <p><%= f.text_field :name, :required => true, class: "mdl-textfield__input" %></p>
  <p><%= f.select :project_id, options_from_collection_for_select(Project.visible, :id, :name, @domain.project_id),
{ include_blank:  true, label: :label_project } %></p>
  <p><%= f.select :status, statuses, { label: :field_status } %></p>
  <p>
    <% if params[:hosting] == '1' && @domain.new_record? -%>
      <%= f.check_box :hosting, checked: true %>
    <% else -%>
      <%= f.check_box :hosting %>
    <% end %>
  </p>
  <p><%= f.check_box :hidden %></p>
  <p><%= f.check_box :checked %></p>
  <p><%= f.text_field(:ending_date, size: 10, required: @domain.ending_date, class: 'ajax-datepicker') %>
    <%= calendar_for('domain_ending_date') %>
  </p>
  <p><%= f.hidden_field :author_id, { value: User.current.id } %></p>
  <% @domain.custom_field_values.each do |value| %>
    <p><%= custom_field_tag_with_label :domain, value %></p>
  <% end %>
  <%= call_hook(:view_domains_form, domain: @domain, form: f) %>
</div>

app/views/domains/_index.html.erb
<h2>
  <div class="contextual">
    <% if params[:hosting] == '1' -%>
      <%= link_to l(:label_hosting_new), { controller: 'domains', action: 'new', params: { hosting: '1' }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% else -%>
      <%= link_to l(:label_domain_new), { controller: 'domains', action: 'new', params: { hosting: '0' }, remote: true }, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <% end %>
  </div>

  <%= link_to l(:tab_domain_all), params.merge({month: '0', hosting: params[:hosting], hidden: '0'}), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <%= link_to l(:tab_domain_month), params.merge({month: '1', hosting: params[:hosting], hidden: '0'}), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect mdl-color-text--white' %>
  <%= link_to l(:tab_domain_hidden), params.merge({hidden: '1', hosting: params[:hosting], month: '0'}), remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--indigo-400 mdl-js-ripple-effect mdl-color-text--white' %>
</h2>

<% unless @domains.nil? -%>
  <div class="autoscroll">
    <table class="list domains mdl-data-table mdl-shadow--1dp">
      <thead>
        <tr>
          <th class="hide-when-print mdl-data-table__cell--non-numeric">
            <%= image_tag('toggle_check.png') %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <% if params[:hosting] == '1' -%>
              <%= l(:label_hosting) %>
            <% else -%>
              <%= l(:label_domain) %>
            <% end %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:label_project) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_status) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_accesses) %>
          </th>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:field_ending_date) %>
          </th>
          <% unless @custom_fields.nil? -%>
            <% @custom_fields.each do |field| -%>
              <th class="mdl-data-table__cell--non-numeric">
                <%= field.name %>
              </th>
            <% end %>
          <% end %>
          <th class="mdl-data-table__cell--non-numeric">
            <%= l(:label_activity) %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @domains.each do |domain| %>
          <tr id="domain-<%= domain.id %>" class="hascontextmenu">
            <td class="hide-when-print mdl-data-table__cell--non-numeric"><%= check_box_tag("ids[]", domain.id, false, :id => nil) %></td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to domain.name, { controller: 'domains', action: 'show',
id: domain, params: { hosting: params[:hosting] } }, remote: true %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <% if domain.project.present? -%>
                <%= link_to domain.project.name, project_path(domain.project) %>
              <% end %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= domain.status %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <% unless domain.accesses.nil? -%>
                <% if domain.project -%>
                  <%= link_to domain.accesses.includes(:category).map(&:category).join(', '), project_accesses_path(domain.project), remote: true %>
                <% else -%>
                  <%= link_to domain.accesses.includes(:category).map(&:category).join(', '), domain_path(domain), remote: true %>
                <% end %>
              <% end %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= format_date(domain.ending_date) %>
            </td>
            <% unless domain.custom_field_values.nil? -%>
              <% domain.custom_field_values.each do |custom_value| -%>
                <td class="mdl-data-table__cell--non-numeric">
                  <%=h show_value(custom_value) %>
                </td>
              <% end %>
            <% end %>
            <td class="mdl-data-table__cell--non-numeric">
              <%= hide_or_show_link(domain) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= context_menu url_for( { controller: 'domains', action: 'context_menu', params: params } ) %>
<% else -%>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/domains/_new.html.erb
<h2>
  <% if params[:hosting] == '1' -%>
    <%= link_to l(:label_hosting_plural), { controller: 'domains', action: 'index', params: { hosting: '1' } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
    <button class='mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect'>
      <%=l(:label_hosting_new) %>
    </button>
  <% else -%>
    <%= link_to l(:label_domain_plural), { controller: 'domains', action: 'index', params: { hosting: '0' } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
    <button class='mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--purple-400 mdl-js-ripple-effect'>
      <%=l(:label_domain_new) %>
    </button>
  <% end %>
</h2>

<%= labelled_form_for :domain, @domain, url: { controller: 'domains', action: 'create', params: { hosting: params[:hosting] } }, html: { class: nil, 'data-remote' => 'true' } do |f| -%>
	<%= render partial: 'form', locals: { f: f } %>
	<h2>
    <%= submit_tag l(:button_create), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
    <%= submit_tag l(:button_create_and_continue), name: 'continue', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color-text--white' %>
  </h2>
<% end -%>

app/views/domains/_show.html.erb
<h2>
  <% if params[:hosting] == '1' -%>
    <%= link_to l(:label_hosting_plural), { controller: 'domains', action: 'index', params: { hosting: '1' } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <% else -%>
    <%= link_to l(:label_domain_plural), { controller: 'domains', action: 'index', params: { hosting: '0' } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--green-400 mdl-js-ripple-effect' %>
  <% end %>
  <% if @domain.hosting -%>
    <%= link_to l(:label_hosting_edit), { controller: 'domains', action: 'edit', id: @domain, params: { hosting: params[:hosting] } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--indigo-400 mdl-js-ripple-effect' %>
  <% else -%>
    <%= link_to l(:label_domain_edit), { controller: 'domains', action: 'edit', id: @domain, params: { hosting: params[:hosting] } }, remote: true, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--indigo-400 mdl-js-ripple-effect' %>
  <% end %>
</h2>

<div class="box">
  <h3>
    <%= domain_title(@domain) %>
    #<%= @domain.id %> <%= @domain.name %>
    <%= @domain.checked? ? l(:field_checked) : nil %>
  </h3>
  <% if @domain.project.present? -%>
    <p><%= l(:field_project) %>: <%= link_to @domain.project.name, project_path(@domain.project) %></p>
  <% end %>
  <p><%= l(:field_status) %>: <%= @domain.status %></p>
  <p><%= l(:field_ending_date) %>: <%= format_date(@domain.ending_date) %></p>
  <% @domain.custom_field_values.each do |custom_value| -%>
    <% unless custom_value.value.blank? -%>
      <p><%= custom_value.custom_field.name%>: <%=h show_value(custom_value) %></p>
    <% end %>
  <% end %>
</div>

<%= render partial: 'accesses/accesses' %>

app/views/domains/context_menu.html.erb
<ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect">
  <% unless @domain.nil? %>
    <li class="mdl-menu__item mdl-js-ripple-effect">
    <li><%= context_menu_link l(:button_edit), { controller: 'domains', action: 'edit', id: @domain, params: params }, class: 'icon-edit' %></li>
    </li>
  <% end %>
</ul>

app/views/domains/create.js.erb
$.ajax({
    type: "POST",
    dataType: "script",
    url: "<%= domain_path(@domain) %>",
    contentType: 'application/json',
    data: JSON.stringify({ params[:domain], _method: 'patch' })
})

app/views/domains/edit.html.erb
<%= render partial: 'edit', locals: { domain: @domain } %>

app/views/domains/index.html.erb
<%= render partial: 'domains' %>

app/views/domains/new.html.erb
<%= render partial: 'new', locals: { domain: @domain } %>

app/views/domains/show.html.erb
<%= render partial: 'show', locals: { domain: @domain } %>

app/views/domains/update.js.erb
$.ajax({
    type: 'POST',
    dataType: 'script',
    url: "<%= domain_path(@domain) %>",
    contentType: 'application/json',
    data: JSON.stringify({ params[:domain], _method: 'patch' })
})